### ISSUE TITLE
composer this package error

### ISSUE THREAD

**Issue by wyt232** [BPing/ffmpeg-push#6]
Installation failed, reverting ./composer.json to its original content.
 how can i do?

**Comment by BPing** [comment]
Add a version tag 
```php 
composer require bping/ffmpeg-push dev-master
```
thanks for your issue

**Comment by wyt232** [comment]
> 添加版本标记
> 
> ```
> 作曲家 需要 bping / ffmpeg - push  dev - master
> ```
> 
> 谢谢你的问题

thanks
