### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by 574252991** [BPing/ffmpeg-push#7]
能有具体的文档吗？能同时间推多个吗？在推多个的同时 怎么指定关闭具体的哪一个

**Comment by BPing** [comment]
抱歉，因为功能不多，readme文档已经算描述了全部内容。所以，不需要额外文档。

推多个流，你可以起多个实例，如：
```php
// 第一条 推流
 $pushUrl1= 'rtmp://pili-publish.heliwebs.com';
 $pushCmd1 = PushVideo::create(); 
 $pushCmd1 ->setOutput(
         PushOutput::create()
             ->setPushUrl($pushUrl1)
     );

// 第二条 推流
 $pushUrl2= 'rtmp://pili-publish.heliwebs.com';
 $pushCmd2 = PushVideo::create(); 
 $pushCmd2 ->setOutput(
         PushOutput::create()
             ->setPushUrl($pushUrl2)
     );
```

```php
//  停止推流，需要异步调用 
// $pushCmd1->stop();    
// $pushCmd2->stop();    
```

不知道符合你的需求不？希望对你有所帮助

**Comment by 574252991** [comment]
你好！感谢你的回复。比如我在前后时间间隔中 推送 2条不是同一时间 ，怎么 关闭指定 一条呢？目前 用现有的文档测试推一条  关闭不了呢？

**Comment by BPing** [comment]
推流会阻塞进程的，所以得异步处理。比如使用swoole框架。

**Comment by 574252991** [comment]
好的 ！感谢，我再看看吧

**Comment by BPing** [comment]
或者你可以直接考虑使用这个包来执行脚本命令
 [symfony/Process](https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Process) : [异步调用命令](https://symfony.com/doc/current/components/process.html#running-processes-asynchronously)

**Comment by 574252991** [comment]
好的！我看看。那你测试这个的时候 是用的什么呢？

**Comment by 574252991** [comment]
主要是没搞过异步这种，思路还停留在同步，一直在用同步考虑这个问题

**Comment by BPing** [comment]
我这边之前是在swoole框架下使用的
